# Generated by Django 6.0.5 on 2026-05-11 09:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=128)),
                ('account_type', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Account',
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('university', models.CharField(max_length=255)),
                ('degree_name', models.CharField(max_length=255)),
                ('years_of_experience', models.IntegerField()),
                ('skills', models.TextField()),
                ('preferred_working_mode', models.CharField(max_length=100)),
                ('preferred_location', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Candidate',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('company_information', models.TextField()),
                ('contact_information', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'Company',
            },
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('work_mode', models.CharField(max_length=100)),
                ('required_yoe', models.IntegerField()),
                ('required_skills', models.TextField()),
                ('required_degree', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('company_email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.company')),
            ],
            options={
                'db_table': 'JobPosting',
            },
        ),
    ]
