# Generated by Django 6.0.5 on 2026-05-26 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_candidate_is_member_company_is_member'),
        ('database', '0002_remove_company_contact_information'),
    ]

    operations = [
    ]
