# Generated by Django 6.0.5 on 2026-05-26 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_merge_20260526_1304'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='contact_information',
            field=models.CharField(default='', max_length=255),
        ),
    ]
